project_name: 'hypotension_0916_ehr_test'
log_base_path: '/hdd1/mjh319/saves'

modification: normal_modificiation

data_path : '/home/mjh319/workspace/numpy4/'
print_option_1 : True 
max_epoch : 50 
batch_size : 128
num_workers: 0
lr : 0.001

pred_lag_list :
    - 300
    - 600
    - 900
multi_list :
    - False
invasive_list : 
    - False
total_exp : 5

colum_ehr : ['age','height', 'weight', 'bmi']
use_ehr : True 















