project_name: 'hypotension_window_test_freq'
log_base_path: '/hdd1/mjh319/saves'

modification: normal_modificiation

data_path : '/hdd2/mjh319/data/hypotension/window_processed/60/'
print_option_1 : True 
max_epoch : 200
batch_size : 128
num_workers: 0
# # lr : 0.001
lr : 0.005

pred_lag_list :
    - 300
multi_list :
    - True
    - False
invasive_list : 
    - True
    - False
total_exp : 1

colum_ehr : ['age','height', 'weight', 'bmi']
use_ehr : True 

window : 6000














